// <auto-generated />
namespace paradise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RebuildQuizSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RebuildQuizSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "202510171557524_RebuildQuizSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
