//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paradise.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class paradiseEntities : DbContext
    {
        public paradiseEntities()
            : base("name=paradiseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course_chapters> course_chapters { get; set; }
        public virtual DbSet<course_enrollments> course_enrollments { get; set; }
        public virtual DbSet<course_lessons> course_lessons { get; set; }
        public virtual DbSet<course_reviews> course_reviews { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<lesson_contents> lesson_contents { get; set; }
        public virtual DbSet<lesson_progress> lesson_progress { get; set; }
        public virtual DbSet<lesson_quizzes> lesson_quizzes { get; set; }
        public virtual DbSet<quiz_attempt_answers> quiz_attempt_answers { get; set; }
        public virtual DbSet<quiz_attempts> quiz_attempts { get; set; }
        public virtual DbSet<quiz_options> quiz_options { get; set; }
        public virtual DbSet<quiz_questions> quiz_questions { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<topic> topics { get; set; }
        public virtual DbSet<user_profiles> user_profiles { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
