//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paradise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson_quizzes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lesson_quizzes()
        {
            this.quiz_attempts = new HashSet<quiz_attempts>();
            this.quiz_questions = new HashSet<quiz_questions>();
        }
    
        public long id { get; set; }
        public long lesson_id { get; set; }
        public string quiz_title { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual course_lessons course_lessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_attempts> quiz_attempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_questions> quiz_questions { get; set; }
    }
}
